#!/bin/bash
#
# HyperNova server management framework
#
# Agent/RHEL init script
#
# Copyright (c) 2012 TDM Ltd
#                    Luke Carrier <luke.carrier@tdm.info>
#
# chkconfig:   - 85 15
# description: The HyperNova agent daemon (hn-agent) provides secure
#              remote server administration via hn-client and web
#              applications.
# processname: hn-agent
# config:      /usr/local/hypernova/etc/hypernova/agent/base.ini
# config:      /usr/local/hypernova/etc/hypernova/agent/local.ini
# pidfile:     /usr/local/hypernova/var/run/hypernova/agent.pid

. /etc/rc.d/init.d/functions
. /etc/sysconfig/network

BIN='/usr/local/hypernova/bin/hn-agent'
PROG="$(basename "$BIN")"
ETC='/usr/local/hypernova/etc/agent'
SYSETC='/etc/sysconfig/hn-agent'
PID='/usr/local/hypernova/var/run/agent.pid'
USER='hnagent'

[ -f "$SYSETC" ] && . "$SYSETC"

stop() {
    echo -n $"Stopping $PROG: "

    pid="$(cat "$PID")"
    kill -3 "$pid" &>/dev/null
    sleep 0.5

    kill -0 "$pid" &>/dev/null && failure || success
    retval=$?

    echo
}

start() {
    echo -n $"Starting $PROG: "

    pid="$(cat "$PID")"
    kill -0 "$pid" &>/dev/null
    if [ "$?" = "0" ]; then
        # pid is already alive
        failure
    else
        su -c "$BIN " "$USER"
        retval=$?

        sleep 0.5
        pid="$(cat "$PID")"
        kill -0 "$pid" && success || failure
    fi

    echo
}

status() {
    echo -n "$PROG is "

    if [ -f "$PID" ]; then
        pid="$(cat "$PID")"
        ps -p "$pid" >/dev/null 2>&1

        if [ "$?" = "0" ]; then
            echo 'running'
        else
            echo 'not running'
        fi
    else
        echo 'not running'
    fi
}

help() {
    echo "$0 start|stop|restart|reload|force-reload|status"
}

case "$1" in
    'start')
        start
        ;;

    'stop')
        stop
        ;;

    'restart'|'reload'|'force-reload')
        stop
        start
        ;;

    'status')
        status
        ;;

    *)
        help
        ;;
esac
